image: node:16

stages:
  - publish
  - doc

publish:
  stage: publish
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - main

doc:
  stage: doc
  script:
    # - rm -rf public
    # - mkdir public
    # - cp -r ./docs public
    # -------
    - npm install
    - npm run jsDoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - main
