image: node:latest

stages:
  - deploy
  - pages

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish

pages:
  stage: pages
  script:
    - npm install
    - npm run build
    - mkdir public
    - cp -r ./docs public
  artifacts:
    paths:
      - public
  only:
    - main
