image: node:16

stages:
  - pages

pages:
  stage: pages
  script:
    - npm install
    - npm run jsDoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - main
