image: node:latest

stages:
  - deploy
  - pages

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - main

pages:
  stage: pages
  script:
    - rm -rf public
    - mkdir public
    - cp -r ./docs/@201flaviosilva public
    - cp -r ./docs/index.html public
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
