image: node:16

stages:
  - doc

doc:
  stage: doc
  script:
    # - rm -rf public
    # - mkdir public
    # - cp -r ./docs public
    # -------
    - npm install
    - npm run jsDoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - release
