name: Export Vanilla

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  export:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd ./lib/Vanilla

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: "201flaviosilva-utils"
          path: build
